# This workflow will check for Maven projects if the licenses of all (transitive) dependencies are vetted.

name: License vetting status check

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR #"
        type: number
        required: false
      branch:
        description: "branch"
        type: string
        required: false
  issue_comment:
    types: [created]
    
jobs:
  call-mvn-license-check:
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    with:
      ref: >
        ${{
          inputs.pr_number && format('refs/pull/{0}/head', inputs.pr_number) ||
          inputs.branch ||
          github.ref
        }}
      projectId: tools.pdt
      javaVersion: 21
    secrets:
      gitlabAPIToken: ${{ secrets.GITLAB_API_TOKEN }}
    permissions:
      pull-requests: write
